version: "3.7"
services:

  # schiffeversenken-database
  schiffeversenken-database:
    image: postgres:latest
    container_name: schiffeversenken-database
    ports:
      - 5433:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: schiffeversenken
      POSTGRES_PASSWORD: schiffeversenken
      POSTGRES_DB: schiffeversenken
    restart: always