version: "3.7"
services:

  # schiffezerstoeren-database
  schiffezerstoeren-database:
    image: postgres:latest
    container_name: schiffezerstoeren-database
    ports:
      - 5433:5432
    environment:
      TZ: Europe/Berlin
      POSTGRES_USER: schiffezerstoeren
      POSTGRES_PASSWORD: schiffezerstoeren
      POSTGRES_DB: schiffezerstoeren
    restart: always